<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="availability only configurable-variation-qty" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" style="display:none;width: 412px;height: 21px;margin: 26px 48px 8px 40px;font-family: Inter-Regular_;font-size: 14px;font-weight: 500;font-stretch: normal;font-style: normal;line-height: 1.5;letter-spacing: 0.25px;color: #037827;
">
    <!-- todo: extrair css -->
    <?= /* @noEscape */ __('%1 In Stock', "<strong>%1</strong>") ?>
</div>
