<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()) : ?>
    <div class="availability only" title="<?= $block->escapeHtmlAttr(__('%1 In Stock', ($block->getStockQtyLeft())))?>">
        <?= /* @noEscape */ __('%1 In Stock', "<strong>{$block->escapeHtml($block->getStockQtyLeft())}</strong>") ?>
    </div>
<?php endif ?>
